{% set name = "pyomicron" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e31e0e4bf2a308eb833faa93956a142bd1f29552da2c489cabc3cd81bf29ab9f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - omicron-hdf5-merge = omicron.cli.hdf5_merge:main
    - omicron-show = omicron.cli.show:main
    - omicron-process = omicron.cli.process:main
    - omicron-root-merge = omicron.cli.root_merge:main
    - omicron-archive = omicron.cli.archive:main
    - omicron-status = omicron.cli.status:main
    - omicron-merge-with-gaps = omicron.cli.merge_with_gaps:main
    - omicron-metric-day-merge = omicron.cli.metric_day_merge:main

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools
  run:
    - dqsegdb2
    - gwdatafind
    - gwpy >=2.0.0
    - h5py
    - ligo-segments
    - lscsoft-glue >=1.60.0
    - markuppy
    - numpy
    - omicron
    - pycondor
    - python >=3.9
    - python-htcondor
    - python-ldas-tools-framecpp
    - python-ligo-lw >=1.4.0
    - root_base

test:
  requires:
    - pip
    - pytest
  imports:
    - omicron
    - omicron.cli
    - omicron.condor
    - omicron.const
    - omicron.data
    - omicron.io
    - omicron.log
    - omicron.nagios
    - omicron.parameters
    - omicron.segments
    - omicron.utils
  commands:
    # check dependencies
    - python -m pip check
    # run unit tests
    - python -m pytest -ra --pyargs omicron
    # check that scripts were built
    - omicron-hdf5-merge --help
    - omicron-show --help
    - omicron-process --help
    - omicron-root-merge --help
    - omicron-status --help
    - omicron-archive --help
    - omicron-merge-metric-day --help
    - omicron-merge-with-gaps --help

about:
  home: https://github.com/gwpy/pyomicron
  dev_url: https://github.com/gwpy/pyomicron.git
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Python utilities and extensions for the Omicron (C++) GW event trigger generator
  description: |
    This package provides a set of python utilities for gravitational-wave
    detector characterisation and data quality. It is intended for use by
    the International Gravitational Wave Network (IGWN) of ground-based
    detectors, along with the Omicron (C++) package.

extra:
  recipe-maintainers:
    - alurban
    - duncanmmacleod
    - areeda
    - eagoetz
    - robertbruntz
